name: 'Go BuildStrap'
description: 'Run series of docker api calls for CICD purposes'
runs:
  # test if static binary will load
  #using: 'alpine' #(Parameter ''using: alpine' is not supported, use 'docker' or 'node12' instead.')
  using: 'docker'
  image: 'docker://alpine:latest'
  #main: 'buildstrap' #  Unexpected value 'main'
  #entrypoint: '/bin/sh -c'
  args:
    - 'ls'
    - '-alh'
    - '/github/workspace'
    - '/github/home'
    - '/github/workflow'
    - '/github/file_commands'

# /usr/bin/docker run --name alpinelatest_REDACTED --label REDACTED --workdir /github/workspace --rm 
# -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER 
# -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW 
# -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL 
# -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY 
# -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP 
# -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true
# --entrypoint "/bin/sh -c" -v "/var/run/docker.sock":"/var/run/docker.sock" 
# -v "/home/runner/work/_temp/_github_home":"/github/home"                                            # empty
# -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" 
# -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" 
# -v "/home/runner/work/test-github-action-golang/test-github-action-golang":"/github/workspace"      # .git .github
# alpine:latest  

#  using: "composite"
#  steps:
#    - run: echo "Hi"
#      shell: bash
