name: 'Go BuildStrap'
description: 'Run series of docker api calls for CICD purposes'
runs:
  # test if static binary will load
  #using: 'alpine' #(Parameter ''using: alpine' is not supported, use 'docker' or 'node12' instead.')
  using: 'docker'
  image: 'docker://alpine:latest'
  #main: 'buildstrap' #  Unexpected value 'main'
  entrypoint: 'pwd && ls -alh && mount'
  
#  using: "composite"
#  steps:
#    - run: echo "Hi"
#      shell: bash
